"""
utils/customers.py
Customer registry — single source of truth for all STARKos customers.
Add new customers here. pendo_id must match exactly (case-sensitive) in Pendo.
"""

CUSTOMERS = {

    "AVEVA": {
        "schema":    "AVEVA_PUBLIC",
        "pendo_id":  "aveva",
        "go_live":   "2024-03-15",
        "csm":       "Dilip Kumar Rajan",
        "sa":        "Matt Lee",
        "license":   "UBP",
        "goals":     ["Reduce MTTR and escalations", "Understand customer sentiment"],
        "notes":     "Renewal due Nov/Dec 2026. Widget regression issues open (SLC-54848, SLC-55021). Gustavo Cuervo is day-to-day contact. Renewal at risk if quality issues not resolved. SAML security data exposure incident (second occurrence) — Tyler Pinckard must sign off before resuming ingestion.",
        "gcp_hostname": "aveva",
        "benchmark_escalation_pct": 2.0,
    },

    "Hyland": {
        "schema":    "HYLAND_PUBLIC",
        "pendo_id":  "hyland",
        "go_live":   "2025-06-29",
        "csm":       "Dilip Kumar Rajan",
        "sa":        "Yuvraj",
        "license":   "CoreSX + ResolveSX (Resolve Assist + Response Assist) + ICA (Assign) + ElevateSX",
        "goals":     [
            "Resolve Assist and Response Assist adoption",
            "ICA intelligent case routing (Assign module)",
            "Elevate QA and agent coaching",
            "Genesys chatbot integration",
            "MCP/Claude connector",
        ],
        "notes":     "Key contacts: Mindy Hamilton (day-to-day), Aaron Weiderman. Multiple active workstreams. Resolve Assist live Jun 29. Assign keyword generation complete — pending Aaron review. Elevate onboarding via weekly Thursday call. Genesys sandbox not feasible — evaluating live session alternative. Salesforce writeback 500 errors (OAuth/ConnectedApp issue). Chose SupportLogic over AptEdge (competitor).",
        "gcp_hostname": "hyland",
        "benchmark_escalation_pct": 2.0,
    },

    "NICE": {
        "schema":    "NICE_PUBLIC",
        "pendo_id":  "nice",
        "go_live":   "2022-01-01",
        "csm":       "Manochitra Janakaraj",
        "sa":        "Tali Bartal",
        "license":   "CoreSX + ResolveSX + ElevateSX",
        "goals":     [
            "Escalation detection and prevention",
            "ResolveSX knowledge search adoption",
            "Elevate SX QA and agent coaching",
            "MCP Beta integration",
        ],
        "notes":     "Key contacts: Inbal Yavin-Partel, Jake Hoeks, Chris Romrell, Dawn Marshall. SAML cert renewal required periodically (Auth0 automated alert 14-21 days prior). MCP Beta requested Jun 2026 — being explored. New Resolution fields requested for CoreSX mapping. Salesforce Milestone for SLA compliance in progress (Jana). 1M+ cases.",
        "gcp_hostname": "nice",
        "benchmark_escalation_pct": 2.0,
    },

    "Saviynt": {
        "schema":    "SAVIYNT_PUBLIC",
        "pendo_id":  "saviynt",
        "go_live":   "2026-05-19",
        "ica_live":  "2026-05-21",
        "csm":       "Melanie Daniels",
        "sa":        "Noppol Setobol",
        "license":   "CoreSX + ICA (Case Routing) + Account Health Summarization",
        "goals":     [
            "Intelligent case routing (ICA) for US East cases",
            "Escalation detection and prevention",
            "Sentiment analysis across all cases",
            "Account health summarization adoption",
        ],
        "notes":     "Key contacts: Pankaj Vora (sponsor), Madhavan Murugesan (SL champion), Gurumurthy. $105k ARR (expanded from $55k Apr 2026). 20-month term May 2026–Jan 2028. Renewal Jan 2027. Open: Account Health Score accuracy (ticket 9520), text-based alerts (ticket 9660), WFM tool integration, MCP Beta in exploration. Fivetran sync delays flagged multiple times.",
        "gcp_hostname": "saviynt",
        "benchmark_escalation_pct": 2.0,
    },

    "BlueGrace": {
        "schema":    "BLUEGRACE_PUBLIC",
        "pendo_id":  "bluegrace",
        "go_live":   "2025-08-01",
        "csm":       "Dilip Kumar Rajan",
        "sa":        "Sam Wade",
        "license":   "CoreSX",
        "goals":     [
            "Real-time signal monitoring for freight operations",
            "Escalation detection",
            "Power BI integration via Data Cloud",
            "SLA business-hours feature (pending roadmap)",
        ],
        "notes":     "Key contact: Kyle Pendergrass. Renewal confirmed. Salesforce re-auth required after credential rotation. Signal spike (Needs Attention/Positive) under investigation — 9.9.0 embedding classifier change impacted signals. SLA business-hours top request for 1+ year. ACE legacy usage — potential Elevate transition. 851K cases.",
        "gcp_hostname": "bluegrace",
        "benchmark_escalation_pct": 2.0,
    },

    "Basware": {
        "schema":    "BASWARE_PUBLIC",
        "pendo_id":  "Basware",
        "go_live":   None,
        "csm":       "Dilip Kumar Rajan",
        "sa":        "Thomas Evans",
        "license":   "CoreSX + Expand + Assist",
        "goals":     [
            "Escalation detection and prevention",
            "Sentiment analysis across all cases",
            "Case cohort summaries via Assist",
            "Expand module adoption",
        ],
        "notes":     "Support team: Melvin, Subiksha, Eugine, Balaji. AE: Thomas Evans. Low customer engagement — Sales involved at leadership level. 914K cases.",
        "gcp_hostname": "basware",
        "benchmark_escalation_pct": 2.0,
    },

    "Alteryx": {
        "schema":    "ALTERYX_PUBLIC",
        "pendo_id":  "alteryx",
        "go_live":   "2022-01-01",
        "csm":       "Melanie Daniels",
        "sa":        "Thomas Evans",
        "license":   "CoreSX",
        "goals":     [
            "Escalation detection and prevention",
            "Sentiment monitoring",
        ],
        "notes":     "CSM: Melanie Daniels. Fivetran connector re-auth required periodically (broken Jun 2026 — customer coordinating IT). Alerts not firing issue reported (ticket 10374). 412K cases. First case from Dec 2011 (historical import).",
        "gcp_hostname": "alteryx",
        "benchmark_escalation_pct": 2.0,
    },

    "Infoblox": {
        "schema":    "INFOBLOX_PUBLIC",
        "pendo_id":  "infoblox",
        "go_live":   "2023-01-01",
        "csm":       "Manochitra Janakaraj",
        "sa":        "Thomas Evans",
        "license":   "CoreSX + ICA",
        "goals":     [
            "Intelligent case assignment (ICA)",
            "Escalation detection",
            "CRM writeback (LTE + sentiment signals)",
        ],
        "notes":     "Key contacts: Guy (technical), Allen. Fivetran reliability concerns — customer wants alternative connector. ACA heavily relied upon. Salesforce integration issue (RCA shared Jun 2026). Custom Object writeback requested (LTE, sentiment, signals). UWF batch_limit fix applied (<200). API container on infoblox-mordor not infoblox-backend. 292K cases.",
        "gcp_hostname": "infoblox-mordor",
        "benchmark_escalation_pct": 2.0,
    },

    "TraceLink": {
        "schema":    "TRACELINK_PUBLIC",
        "pendo_id":  "tracelink",
        "go_live":   "2026-07-20",
        "csm":       "Manochitra Janakaraj",
        "sa":        "Thomas Evans",
        "license":   "ResolveSX",
        "goals":     [
            "ResolveSX knowledge search from Salesforce + Jira + Confluence",
            "Resolve Assist for agents",
        ],
        "notes":     "Key contacts: Renato Fornaroli, Ankit Solanki. ResolveSX implementation in progress. Credentials for Confluence/Jira delayed — fallback to Salesforce-only. Role mapping patched. Google Chat webhook for alerts requested. Public documentation ingestion requested (additional PS charge TBD). Weekly Wednesday status calls.",
        "gcp_hostname": "tracelink",
        "benchmark_escalation_pct": 2.0,
    },

    "CyberArk": {
        "schema":    "CYBERARK_PUBLIC",
        "pendo_id":  "cyberark",
        "go_live":   None,
        "csm":       "Melanie Daniels",
        "sa":        "Greg",
        "license":   "CoreSX + Assist",
        "goals":     [],
        "notes":     "CHURN RISK: Palo Alto Networks (PANW) acquired CyberArk and decided to discontinue SupportLogic — building internal solution. Contract runs until Aug 2026 (Salesforce migration). Contract non-cancellable through Dec 2027 ($310k/yr). Melanie pursuing executive-level business review to retain logo. Contact: Paul Kozlov (day-to-day), Yaron (procurement). 1.4M cases.",
        "gcp_hostname": "cyberark",
        "benchmark_escalation_pct": 2.0,
    },

    "Demo3": {
        "schema":    "DEMO3_PUBLIC",
        "pendo_id":  "demo3",
        "go_live":   None,
        "csm":       "",
        "sa":        "",
        "license":   "Demo",
        "goals":     [],
        "notes":     "Demo environment for internal testing and prospect demos.",
        "gcp_hostname": "demo3",
        "benchmark_escalation_pct": 2.0,
    },

    "Cvent": {
        "schema":    "CVENT_PUBLIC",
        "pendo_id":  "cvent",
        "go_live":   None,
        "csm":       "",
        "sa":        "",
        "license":   "CoreSX + ElevateSX",
        "goals":     [],
        "notes":     "Also has cvent_elevate_api and elevateplus_cvent schemas. Check which is primary.",
        "gcp_hostname": "cvent",
        "benchmark_escalation_pct": 2.0,
    },

    "NTT Data": {
        "schema":    "NTTLTD_EU_PUBLIC",
        "pendo_id":  "nttltd",
        "go_live":   None,
        "csm":       "",
        "sa":        "",
        "license":   "CoreSX",
        "goals":     [],
        "notes":     "Two schemas available: nttltd_eu_public (EU) and nttsea_public (SEA). Dashboard uses SEA by default — update schema field if EU is needed.",
        "gcp_hostname": "nttsea",
        "benchmark_escalation_pct": 2.0,
    },

    "Coupa": {
        "schema":    "COUPA_PUBLIC",
        "pendo_id":  "coupa",
        "go_live":   None,
        "csm":       "",
        "sa":        "",
        "license":   "CoreSX",
        "goals":     [],
        "notes":     "",
        "gcp_hostname": "coupa",
        "benchmark_escalation_pct": 2.0,
    },

    "Q2": {
        "schema":    "Q2_PUBLIC",
        "pendo_id":  "q2",
        "go_live":   None,
        "csm":       "",
        "sa":        "",
        "license":   "CoreSX + ElevateSX",
        "goals":     [],
        "notes":     "Also has q2_elevate_api and elevateplus_q2 schemas.",
        "gcp_hostname": "q2",
        "benchmark_escalation_pct": 2.0,
    },

    "Proofpoint": {
        "schema":    "PROOFPOINT_PUBLIC",
        "pendo_id":  "proofpoint",
        "go_live":   None,
        "csm":       "",
        "sa":        "",
        "license":   "CoreSX + ElevateSX",
        "goals":     [],
        "notes":     "Also has proofpoint_elevate_api schema.",
        "gcp_hostname": "proofpoint",
        "benchmark_escalation_pct": 2.0,
    },

    "ESRI": {
        "schema":    "ESRI_PUBLIC",
        "pendo_id":  "esri",
        "go_live":   None,
        "csm":       "",
        "sa":        "",
        "license":   "CoreSX",
        "goals":     [],
        "notes":     "",
        "gcp_hostname": "esri",
        "benchmark_escalation_pct": 2.0,
    },

    "Litera": {
        "schema":    "LITERA_PUBLIC",
        "pendo_id":  "litera",
        "go_live":   None,
        "csm":       "",
        "sa":        "",
        "license":   "CoreSX",
        "goals":     [],
        "notes":     "",
        "gcp_hostname": "litera",
        "benchmark_escalation_pct": 2.0,
    },

}
