"""
utils/customers.py
Customer registry — single source of truth for all STARKos customers.
Add new customers here. pendo_id must match exactly (case-sensitive) in Pendo.
"""

CUSTOMERS = {

    "AVEVA": {
        "schema":    "AVEVA_PUBLIC",
        "pendo_id":  "aveva",
        "pendo_ids": ['aveva', 'Aveva', 'AVEVA'],
        "go_live":   "2024-03-15",
        "csm":       "Dilip Kumar Rajan",
        "sa":        "Matt Lee",
        "license":   "UBP",
        "goals":     ["Reduce MTTR and escalations", "Understand customer sentiment"],
        "notes":     "Renewal due Nov/Dec 2026. Widget regression issues open (SLC-54848, SLC-55021). Gustavo Cuervo is day-to-day contact. Renewal at risk if quality issues not resolved. SAML security data exposure incident (second occurrence) — Tyler Pinckard must sign off before resuming ingestion.",
        "gcp_hostname": "aveva",
        "benchmark_escalation_pct": 2.0,
    },

    "Hyland": {
        "schema":    "HYLAND_PUBLIC",
        "pendo_id":  "hyland",
        "pendo_ids": ['hyland', 'Hyland'],
        "go_live":   "2025-06-29",
        "csm":       "Dilip Kumar Rajan",
        "sa":        "Yuvraj",
        "license":   "CoreSX + ResolveSX (Resolve Assist + Response Assist) + ICA (Assign) + ElevateSX",
        "goals":     [
            "Resolve Assist and Response Assist adoption",
            "ICA intelligent case routing (Assign module)",
            "Elevate QA and agent coaching",
            "Genesys chatbot integration",
            "MCP/Claude connector",
        ],
        "notes":     "Key contacts: Mindy Hamilton (day-to-day), Aaron Weiderman. Multiple active workstreams. Resolve Assist live Jun 29. Assign keyword generation complete — pending Aaron review. Elevate onboarding via weekly Thursday call. Genesys sandbox not feasible — evaluating live session alternative. Salesforce writeback 500 errors (OAuth/ConnectedApp issue). Chose SupportLogic over AptEdge (competitor).",
        "gcp_hostname": "hyland",
        "benchmark_escalation_pct": 2.0,
    },

    "NICE": {
        "schema":    "NICE_PUBLIC",
        "xfind_schemas": ["NICE_PUBLIC"],
        "pendo_id":  "nice",
        "pendo_ids": ['nice', 'Nice', 'NICE'],
        "go_live":   "2022-01-01",
        "csm":       "Manochitra Janakaraj",
        "sa":        "Tali Bartal",
        "license":   "CoreSX + ResolveSX + ElevateSX",
        "goals":     [
            "Escalation detection and prevention",
            "ResolveSX knowledge search adoption",
            "Elevate SX QA and agent coaching",
            "MCP Beta integration",
        ],
        "notes":     "Key contacts: Inbal Yavin-Partel, Jake Hoeks, Chris Romrell, Dawn Marshall. SAML cert renewal required periodically (Auth0 automated alert 14-21 days prior). MCP Beta requested Jun 2026 — being explored. New Resolution fields requested for CoreSX mapping. Salesforce Milestone for SLA compliance in progress (Jana). 1M+ cases.",
        "gcp_hostname": "nice",
        "benchmark_escalation_pct": 2.0,
    },

    "Saviynt": {
        "schema":    "SAVIYNT_PUBLIC",
        "pendo_id":  "saviynt",
        "pendo_ids": ['saviynt', 'Saviynt'],
        "go_live":   "2026-05-19",
        "ica_live":  "2026-05-21",
        "csm":       "Melanie Daniels",
        "sa":        "Noppol Setobol",
        "license":   "CoreSX + ICA (Case Routing) + Account Health Summarization",
        "goals":     [
            "Intelligent case routing (ICA) for US East cases",
            "Escalation detection and prevention",
            "Sentiment analysis across all cases",
            "Account health summarization adoption",
        ],
        "notes":     "Key contacts: Pankaj Vora (sponsor), Madhavan Murugesan (SL champion), Gurumurthy. $105k ARR (expanded from $55k Apr 2026). 20-month term May 2026–Jan 2028. Renewal Jan 2027. Open: Account Health Score accuracy (ticket 9520), text-based alerts (ticket 9660), WFM tool integration, MCP Beta in exploration. Fivetran sync delays flagged multiple times.",
        "gcp_hostname": "saviynt",
        "benchmark_escalation_pct": 2.0,
    },

    "BlueGrace": {
        "schema":    "BLUEGRACE_PUBLIC",
        "pendo_id":  "bluegrace",
        "pendo_ids": ['bluegrace', 'Bluegrace'],
        "go_live":   "2025-08-01",
        "csm":       "Dilip Kumar Rajan",
        "sa":        "Sam Wade",
        "license":   "CoreSX",
        "goals":     [
            "Real-time signal monitoring for freight operations",
            "Escalation detection",
            "Power BI integration via Data Cloud",
            "SLA business-hours feature (pending roadmap)",
        ],
        "notes":     "Key contact: Kyle Pendergrass. Renewal confirmed. Salesforce re-auth required after credential rotation. Signal spike (Needs Attention/Positive) under investigation — 9.9.0 embedding classifier change impacted signals. SLA business-hours top request for 1+ year. ACE legacy usage — potential Elevate transition. 851K cases.",
        "gcp_hostname": "bluegrace",
        "benchmark_escalation_pct": 2.0,
    },

    "Basware": {
        "schema":    "BASWARE_PUBLIC",
        "pendo_id":  "Basware",
        "go_live":   None,
        "csm":       "Dilip Kumar Rajan",
        "sa":        "Thomas Evans",
        "license":   "CoreSX + Expand + Assist",
        "goals":     [
            "Escalation detection and prevention",
            "Sentiment analysis across all cases",
            "Case cohort summaries via Assist",
            "Expand module adoption",
        ],
        "notes":     "Support team: Melvin, Subiksha, Eugine, Balaji. AE: Thomas Evans. Low customer engagement — Sales involved at leadership level. 914K cases.",
        "gcp_hostname": "basware",
        "benchmark_escalation_pct": 2.0,
    },

    "Alteryx": {
        "schema":    "ALTERYX_PUBLIC",
        "pendo_id":  "alteryx",
        "pendo_ids": ['alteryx', 'Alteryx'],
        "go_live":   "2022-01-01",
        "csm":       "Melanie Daniels",
        "sa":        "Thomas Evans",
        "license":   "CoreSX",
        "goals":     [
            "Escalation detection and prevention",
            "Sentiment monitoring",
        ],
        "notes":     "CSM: Melanie Daniels. Fivetran connector re-auth required periodically (broken Jun 2026 — customer coordinating IT). Alerts not firing issue reported (ticket 10374). 412K cases. First case from Dec 2011 (historical import).",
        "gcp_hostname": "alteryx",
        "benchmark_escalation_pct": 2.0,
    },

    "Infoblox": {
        "schema":    "INFOBLOX_PUBLIC",
        "pendo_id":  "infoblox",
        "pendo_ids": ['infoblox', 'Infoblox'],
        "go_live":   "2023-01-01",
        "csm":       "Manochitra Janakaraj",
        "sa":        "Thomas Evans",
        "license":   "CoreSX + ICA",
        "goals":     [
            "Intelligent case assignment (ICA)",
            "Escalation detection",
            "CRM writeback (LTE + sentiment signals)",
        ],
        "notes":     "Key contacts: Guy (technical), Allen. Fivetran reliability concerns — customer wants alternative connector. ACA heavily relied upon. Salesforce integration issue (RCA shared Jun 2026). Custom Object writeback requested (LTE, sentiment, signals). UWF batch_limit fix applied (<200). API container on infoblox-mordor not infoblox-backend. 292K cases.",
        "gcp_hostname": "infoblox-mordor",
        "benchmark_escalation_pct": 2.0,
    },

    "TraceLink": {
        "schema":    "TRACELINK_PUBLIC",
        "pendo_id":  "tracelink",
        "pendo_ids": ['tracelink', 'Tracelink'],
        "go_live":   "2026-07-20",
        "csm":       "Manochitra Janakaraj",
        "sa":        "Thomas Evans",
        "license":   "ResolveSX",
        "goals":     [
            "ResolveSX knowledge search from Salesforce + Jira + Confluence",
            "Resolve Assist for agents",
        ],
        "notes":     "Key contacts: Renato Fornaroli, Ankit Solanki. ResolveSX implementation in progress. Credentials for Confluence/Jira delayed — fallback to Salesforce-only. Role mapping patched. Google Chat webhook for alerts requested. Public documentation ingestion requested (additional PS charge TBD). Weekly Wednesday status calls.",
        "gcp_hostname": "tracelink",
        "benchmark_escalation_pct": 2.0,
    },

    "CyberArk": {
        "schema":    "CYBERARK_PUBLIC",
        "pendo_id":  "cyberark",
        "pendo_ids": ['cyberark', 'Cyberark'],
        "go_live":   None,
        "csm":       "Melanie Daniels",
        "sa":        "Greg",
        "license":   "CoreSX + Assist",
        "goals":     [],
        "notes":     "CHURN RISK: Palo Alto Networks (PANW) acquired CyberArk and decided to discontinue SupportLogic — building internal solution. Contract runs until Aug 2026 (Salesforce migration). Contract non-cancellable through Dec 2027 ($310k/yr). Melanie pursuing executive-level business review to retain logo. Contact: Paul Kozlov (day-to-day), Yaron (procurement). 1.4M cases.",
        "gcp_hostname": "cyberark",
        "benchmark_escalation_pct": 2.0,
    },

    "Demo3": {
        "schema":    "DEMO3_PUBLIC",
        "pendo_id":  "demo3",
        "pendo_ids": ['demo3', 'Demo3'],
        "go_live":   None,
        "csm":       "",
        "sa":        "",
        "license":   "Demo",
        "goals":     [],
        "notes":     "Demo environment for internal testing and prospect demos.",
        "gcp_hostname": "demo3",
        "benchmark_escalation_pct": 2.0,
    },

    "Cvent": {
        "schema":    "CVENT_PUBLIC",
        "xfind_schemas": ["CVENTAGENT_PUBLIC", "CVENTPORTAL_PUBLIC"],
        "pendo_id":  "cvent",
        "pendo_ids": ['cvent', 'Cvent'],
        "go_live":   None,
        "csm":       "",
        "sa":        "",
        "license":   "CoreSX + ElevateSX",
        "goals":     [],
        "notes":     "Also has cvent_elevate_api and elevateplus_cvent schemas. Check which is primary.",
        "gcp_hostname": "cvent",
        "benchmark_escalation_pct": 2.0,
    },

    "NTT Data": {
        "schema":    "NTTLTD_EU_PUBLIC",
        "pendo_id":  "NTT DATA",
        "pendo_ids": ['NTT DATA', 'NTTDATA'],
        "go_live":   None,
        "csm":       "",
        "sa":        "",
        "license":   "CoreSX",
        "goals":     [],
        "notes":     "Two schemas available: nttltd_eu_public (EU) and nttsea_public (SEA). Dashboard uses SEA by default — update schema field if EU is needed.",
        "gcp_hostname": "nttsea",
        "benchmark_escalation_pct": 2.0,
    },

    "Coupa": {
        "schema":    "COUPA_PUBLIC",
        "pendo_id":  "Coupa",
        "go_live":   None,
        "csm":       "",
        "sa":        "",
        "license":   "CoreSX",
        "goals":     [],
        "notes":     "",
        "gcp_hostname": "coupa",
        "benchmark_escalation_pct": 2.0,
    },

    "Q2": {
        "schema":    "Q2_PUBLIC",
        "pendo_id":  "q2",
        "pendo_ids": ['q2', 'Q2'],
        "go_live":   None,
        "csm":       "",
        "sa":        "",
        "license":   "CoreSX + ElevateSX",
        "goals":     [],
        "notes":     "Also has q2_elevate_api and elevateplus_q2 schemas.",
        "gcp_hostname": "q2",
        "benchmark_escalation_pct": 2.0,
    },

    "Proofpoint": {
        "schema":    "PROOFPOINT_PUBLIC",
        "pendo_id":  "proofpoint",
        "pendo_ids": ['proofpoint', 'Proofpoint'],
        "go_live":   None,
        "csm":       "",
        "sa":        "",
        "license":   "CoreSX + ElevateSX",
        "goals":     [],
        "notes":     "Also has proofpoint_elevate_api schema.",
        "gcp_hostname": "proofpoint",
        "benchmark_escalation_pct": 2.0,
    },

    "ESRI": {
        "schema":    "ESRI_PUBLIC",
        "pendo_id":  "esri",
        "pendo_ids": ['esri', 'Esri'],
        "go_live":   None,
        "csm":       "",
        "sa":        "",
        "license":   "CoreSX",
        "goals":     [],
        "notes":     "",
        "gcp_hostname": "esri",
        "benchmark_escalation_pct": 2.0,
    },

    "Litera": {
        "schema":    "LITERA_PUBLIC",
        "pendo_id":  "litera",
        "pendo_ids": ['litera', 'Litera'],
        "go_live":   None,
        "csm":       "",
        "sa":        "",
        "license":   "CoreSX",
        "goals":     [],
        "notes":     "",
        "gcp_hostname": "litera",
        "benchmark_escalation_pct": 2.0,
    },

    "CrowdStrike": {
        "schema":    "CROWDSTRIKE_PUBLIC",
        "pendo_id":  "crowdstrike",
        "pendo_ids": ['crowdstrike', 'Crowdstrike', 'CrowdStrike'],
        "go_live":   "2024-01-01",
        "csm":       "",
        "sa":        "",
        "license":   "CoreSX",
        "goals":     [],
        "notes":     "722K cases. Data from Jan 2024.",
        "gcp_hostname": "crowdstrike",
        "benchmark_escalation_pct": 2.0,
    },

    "Automation Anywhere": {
        "schema":    "AUTOMATIONANYWHERE_PUBLIC",
        "pendo_id":  "automationanywhere",
        "pendo_ids": ['automationanywhere', 'Automation Anywhere'],
        "go_live":   "2022-06-24",
        "csm":       "Kathleen Garcia",
        "sa":        "",
        "license":   "CoreSX + Assign + Elevate",
        "goals":     [],
        "notes":     "440K cases. AE: Jessica Voss. Renewal Jun 2027.",
        "gcp_hostname": "automationanywhere",
        "benchmark_escalation_pct": 2.0,
    },

    "Qlik": {
        "schema":    "QLIK2_PUBLIC",
        "pendo_id":  "qlik",
        "pendo_ids": ['qlik', 'Qlik'],
        "go_live":   None,
        "csm":       "",
        "sa":        "",
        "license":   "CoreSX",
        "goals":     [],
        "notes":     "408K cases.",
        "gcp_hostname": "qlik2",
        "benchmark_escalation_pct": 2.0,
    },

    "Rubrik": {
        "schema":    "RUBRIK_PUBLIC",
        "pendo_id":  "rubrik",
        "pendo_ids": ['rubrik', 'Rubrik'],
        "go_live":   None,
        "csm":       "",
        "sa":        "",
        "license":   "CoreSX + ElevateSX",
        "goals":     [],
        "notes":     "861K cases.",
        "gcp_hostname": "rubrik",
        "benchmark_escalation_pct": 2.0,
    },

    "F5": {
        "schema":    "F5_PUBLIC",
        "pendo_id":  "F5",
        "go_live":   None,
        "csm":       "",
        "sa":        "",
        "license":   "CoreSX",
        "goals":     [],
        "notes":     "58K cases.",
        "gcp_hostname": "f5",
        "benchmark_escalation_pct": 2.0,
    },

    "Fivetran": {
        "schema":    "FIVETRAN_PUBLIC",
        "pendo_id":  "Fivetran",
        "go_live":   None,
        "csm":       "",
        "sa":        "",
        "license":   "CoreSX",
        "goals":     [],
        "notes":     "340K cases.",
        "gcp_hostname": "fivetran",
        "benchmark_escalation_pct": 2.0,
    },

    "Braze": {
        "schema":    "BRAZE_PUBLIC",
        "pendo_id":  "braze",
        "pendo_ids": ['braze', 'Braze'],
        "go_live":   None,
        "csm":       "",
        "sa":        "",
        "license":   "CoreSX",
        "goals":     [],
        "notes":     "248K cases.",
        "gcp_hostname": "braze",
        "benchmark_escalation_pct": 2.0,
    },

    "Phenom People": {
        "schema":    "PHENOM_PUBLIC",
        "pendo_id":  "phenom",
        "pendo_ids": ['phenom', 'phenom-sn'],
        "go_live":   None,
        "csm":       "",
        "sa":        "",
        "license":   "CoreSX",
        "goals":     [],
        "notes":     "195K cases.",
        "gcp_hostname": "phenom",
        "benchmark_escalation_pct": 2.0,
    },

    "Grafana Labs": {
        "schema":    "GRAFANALABS_PUBLIC",
        "pendo_id":  "grafanalabs",
        "pendo_ids": ['grafanalabs', 'Grafana Labs'],
        "go_live":   None,
        "csm":       "",
        "sa":        "",
        "license":   "CoreSX",
        "goals":     [],
        "notes":     "54K cases.",
        "gcp_hostname": "grafanalabs",
        "benchmark_escalation_pct": 2.0,
    },

    "ABBYY": {
        "schema":    "ABBYY_PUBLIC",
        "pendo_id":  "abbyy",
        "pendo_ids": ['abbyy', 'Abbyy'],
        "go_live":   "2022-01-01",
        "csm":       "",
        "sa":        "",
        "license":   "CoreSX",
        "goals":     [],
        "notes":     "93K cases. Data from Jan 2022.",
        "gcp_hostname": "abbyy",
        "benchmark_escalation_pct": 2.0,
    },

    "Appspace": {
        "schema":    "APPSPACE_PUBLIC",
        "pendo_id":  "Appspace",
        "go_live":   "2023-01-01",
        "csm":       "",
        "sa":        "",
        "license":   "CoreSX",
        "goals":     [],
        "notes":     "37K cases. Data from Jan 2023.",
        "gcp_hostname": "appspace",
        "benchmark_escalation_pct": 2.0,
    },

    "Deep Instinct": {
        "schema":    "DEEPINSTINCT_PUBLIC",
        "pendo_id":  "deepinstinct",
        "pendo_ids": ['deepinstinct', 'Deep Instinct'],
        "go_live":   "2023-01-01",
        "csm":       "",
        "sa":        "",
        "license":   "CoreSX",
        "goals":     [],
        "notes":     "13K cases. Data from Jan 2023.",
        "gcp_hostname": "deepinstinct",
        "benchmark_escalation_pct": 2.0,
    },

    "Freshworks": {
        "schema":    "FRESHWORKS_PUBLIC",
        "pendo_id":  "freshworks",
        "pendo_ids": ['freshworks', 'Freshworks'],
        "go_live":   "2021-01-01",
        "csm":       "",
        "sa":        "",
        "license":   "CoreSX",
        "goals":     [],
        "notes":     "2.2M cases. Data from Jan 2021. Large account.",
        "gcp_hostname": "freshworks",
        "benchmark_escalation_pct": 2.0,
    },

    "Mews": {
        "schema":    "MEWS_PUBLIC",
        "pendo_id":  "mews",
        "pendo_ids": ['mews', 'Mews'],
        "go_live":   "2022-01-01",
        "csm":       "",
        "sa":        "",
        "license":   "CoreSX",
        "goals":     [],
        "notes":     "544K cases. Data from Jan 2022.",
        "gcp_hostname": "mews",
        "benchmark_escalation_pct": 2.0,
    },

    "BigPanda": {
        "schema":    "BIGPANDA_DEVREV1_PUBLIC",
        "pendo_id":  "bigpanda",
        "pendo_ids": ['bigpanda', 'Bigpanda', 'BigPanda'],
        "go_live":   "2025-01-01",
        "csm":       "",
        "sa":        "",
        "license":   "CoreSX",
        "goals":     [],
        "notes":     "14K cases. Data from Jan 2025. DB: bigpanda-devrev1.",
        "gcp_hostname": "bigpanda",
        "benchmark_escalation_pct": 2.0,
    },

    "Databricks": {
        "schema":    "DATABRICKS_PUBLIC",
        "pendo_id":  "Databricks",
        "go_live":   "2022-01-01",
        "csm":       "",
        "sa":        "",
        "license":   "CoreSX",
        "goals":     [],
        "notes":     "242K cases. Data from Jan 2014 (historical import).",
        "gcp_hostname": "databricks",
        "benchmark_escalation_pct": 2.0,
    },

    "Restaurant365": {
        "schema":    "RESTAURANT365_PUBLIC",
        "pendo_id":  "Restaurant365",
        "go_live":   "2022-01-01",
        "csm":       "",
        "sa":        "",
        "license":   "CoreSX",
        "goals":     [],
        "notes":     "1M cases. Data from Jan 2022.",
        "gcp_hostname": "restaurant365",
        "benchmark_escalation_pct": 2.0,
    },

    "BMC": {
        "schema":    "BMC_PUBLIC",
        "pendo_id":  "bmc",
        "pendo_ids": ["bmc", "BMC", "Bmc"],
        "go_live":   "2022-01-01",
        "csm":       "",
        "sa":        "",
        "license":   "CoreSX",
        "goals":     [],
        "notes":     "797K cases. Data from Jan 2022.",
        "gcp_hostname": "bmc",
        "benchmark_escalation_pct": 2.0,
    },

    "HPE Zerto": {
        "schema":    "ZERTO_PUBLIC",
        "pendo_id":  "Zerto",
        "pendo_ids": ["Zerto"],
        "go_live":   "2020-01-01",
        "csm":       "",
        "sa":        "",
        "license":   "CoreSX",
        "goals":     [],
        "notes":     "153K cases. Data from Jan 2020. Pendo account: Zerto.",
        "gcp_hostname": "zerto",
        "benchmark_escalation_pct": 2.0,
    },

    "HPE Nimble Storage": {
        "schema":    "NIMBLESTORAGE_PUBLIC",
        "pendo_id":  "Nimblestorage",
        "pendo_ids": ["Nimblestorage", "Nimble Storage"],
        "go_live":   "2022-01-01",
        "csm":       "",
        "sa":        "",
        "license":   "CoreSX",
        "goals":     [],
        "notes":     "296K cases. Data from Jan 2022. Pendo account: Nimble Storage.",
        "gcp_hostname": "nimblestorage",
        "benchmark_escalation_pct": 2.0,
    },

    "CommScope": {
        "schema":    "COMMSCOPE_PUBLIC",
        "pendo_id":  "Commscope",
        "pendo_ids": ["Commscope"],
        "go_live":   "2022-01-01",
        "csm":       "",
        "sa":        "",
        "license":   "CoreSX",
        "goals":     [],
        "notes":     "1M+ cases. Data from Apr 2010 (historical import). No Pendo iframe data found.",
        "gcp_hostname": "commscope",
        "benchmark_escalation_pct": 2.0,
    },

    "Coveo": {
        "schema":    "COVEO_PUBLIC",
        "pendo_id":  "coveo",
        "pendo_ids": ["coveo", "Coveo", "COVEO"],
        "go_live":   "2020-01-01",
        "csm":       "",
        "sa":        "",
        "license":   "CoreSX",
        "goals":     [],
        "notes":     "40K cases. Data from Jan 2020.",
        "gcp_hostname": "coveo",
        "benchmark_escalation_pct": 2.0,
    },

    "SPS Commerce": {
        "schema":    "SPSCOMMERCE_PUBLIC",
        "pendo_id":  "spscommerce",
        "pendo_ids": ["spscommerce", "SpsCommerce", "SPS Commerce"],
        "go_live":   "2022-01-01",
        "csm":       "",
        "sa":        "",
        "license":   "CoreSX",
        "goals":     [],
        "notes":     "1.4M cases. Data from Jan 2022. Pendo ID unconfirmed.",
        "gcp_hostname": "spscommerce",
        "benchmark_escalation_pct": 2.0,
    },

    "Vercara": {
        "schema":    "NSS_PUBLIC",
        "pendo_id":  "nss",
        "pendo_ids": ["nss", "Nss", "NSS"],
        "go_live":   "2022-01-01",
        "csm":       "",
        "sa":        "",
        "license":   "CoreSX",
        "goals":     [],
        "notes":     "771K cases. Schema: NSS_PUBLIC. Pendo account: nss.",
        "gcp_hostname": "nss",
        "benchmark_escalation_pct": 2.0,
    },

    "Informatica": {
        "schema":    "INFORMATICA_PUBLIC",
        "pendo_id":  "Informatica",
        "pendo_ids": ["Informatica", "informatica", "INFORMATICA"],
        "go_live":   "2022-01-01",
        "csm":       "",
        "sa":        "",
        "license":   "CoreSX",
        "goals":     [],
        "notes":     "594K cases. Data from Jan 2022.",
        "gcp_hostname": "informatica",
        "benchmark_escalation_pct": 2.0,
    },

    "Certinia": {
        "schema":    "CERTINIA_PUBLIC",
        "pendo_id":  "Certinia",
        "pendo_ids": ["Certinia", "certinia", "CERTINIA"],
        "go_live":   "2022-01-01",
        "csm":       "",
        "sa":        "",
        "license":   "CoreSX",
        "goals":     [],
        "notes":     "92K cases. Data from Jan 2022.",
        "gcp_hostname": "certinia",
        "benchmark_escalation_pct": 2.0,
    },

}
